name: mob_novelapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase: ^2.7.0
  supabase_flutter: ^2.9.0
  file_picker: ^10.1.9
  http: ^1.4.0
  google_sign_in: ^6.3.0
  go_router: ^15.1.2
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_provider: ^2.1.0
  font_awesome_flutter: ^10.8.0
  flutter_riverpod: ^2.6.1
  image_cropper: ^9.1.0
  image: ^4.5.4
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/Novel's World Icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/Novel's World Icon.png